"""add status column to invitation model

Revision ID: 06b307d4cfd4
Revises: b041cef628a5
Create Date: 2024-10-09 08:51:16.737000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b307d4cfd4'
down_revision = 'b041cef628a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.create_unique_constraint('uq_invitation_email_organization', ['email', 'organization_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invitation_email_organization', type_='unique')
        batch_op.drop_column('status')

    op.create_table('_alembic_tmp_invitation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('organization_id', sa.INTEGER(), nullable=True),
    sa.Column('inviter_id', sa.INTEGER(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'organization_id', name='_email_organization_uc')
    )
    # ### end Alembic commands ###
