"""Add password reset fields

Revision ID: 0dbfa7061759
Revises: 35d9532a3787
Create Date: 2024-10-01 11:04:16.608774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbfa7061759'
down_revision = '35d9532a3787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expiration', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_reset_password_token'), ['reset_password_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reset_password_token'))
        batch_op.drop_column('reset_password_expiration')
        batch_op.drop_column('reset_password_token')

    # ### end Alembic commands ###
