"""Add service column to APIRequest model

Revision ID: 35d9532a3787
Revises: c3eaedbabbe6
Create Date: 2024-10-01 10:23:44.666628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d9532a3787'
down_revision = 'c3eaedbabbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('apn', sa.String(length=64), nullable=True),
    sa.Column('fips', sa.String(length=64), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_request_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_username', ['username'], unique=1)

    with op.batch_alter_table('api_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_request_timestamp'))

    op.drop_table('api_request')
    # ### end Alembic commands ###
